//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func (in *ContextForge) DeepCopyInto(out *ContextForge) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *ContextForge) DeepCopy() *ContextForge {
	if in == nil {
		return nil
	}
	out := new(ContextForge)
	in.DeepCopyInto(out)
	return out
}

func (in *ContextForge) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ContextForgeList) DeepCopyInto(out *ContextForgeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ContextForge, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *ContextForgeList) DeepCopy() *ContextForgeList {
	if in == nil {
		return nil
	}
	out := new(ContextForgeList)
	in.DeepCopyInto(out)
	return out
}

func (in *ContextForgeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ContextForgeSpec) DeepCopyInto(out *ContextForgeSpec) {
	*out = *in
	in.Gateway.DeepCopyInto(&out.Gateway)
	in.Database.DeepCopyInto(&out.Database)
	in.Redis.DeepCopyInto(&out.Redis)
	if in.Nginx != nil {
		in, out := &in.Nginx, &out.Nginx
		*out = new(NginxSpec)
		(*in).DeepCopyInto(*out)
	}
	in.Auth.DeepCopyInto(&out.Auth)
	if in.Features != nil {
		in, out := &in.Features, &out.Features
		*out = new(FeaturesSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Testing != nil {
		in, out := &in.Testing, &out.Testing
		*out = new(TestingSpec)
		(*in).DeepCopyInto(*out)
	}
}

func (in *ContextForgeSpec) DeepCopy() *ContextForgeSpec {
	if in == nil {
		return nil
	}
	out := new(ContextForgeSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *ContextForgeStatus) DeepCopyInto(out *ContextForgeStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *ContextForgeStatus) DeepCopy() *ContextForgeStatus {
	if in == nil {
		return nil
	}
	out := new(ContextForgeStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *GatewaySpec) DeepCopyInto(out *GatewaySpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Workers != nil {
		in, out := &in.Workers, &out.Workers
		*out = new(int32)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.SessionPoolEnabled != nil {
		in, out := &in.SessionPoolEnabled, &out.SessionPoolEnabled
		*out = new(bool)
		**out = **in
	}
	if in.StreamableHTTPMaxEventsPerStream != nil {
		in, out := &in.StreamableHTTPMaxEventsPerStream, &out.StreamableHTTPMaxEventsPerStream
		*out = new(int32)
		**out = **in
	}
	if in.HTTPXMaxConnections != nil {
		in, out := &in.HTTPXMaxConnections, &out.HTTPXMaxConnections
		*out = new(int32)
		**out = **in
	}
	if in.HTTPXMaxKeepaliveConnections != nil {
		in, out := &in.HTTPXMaxKeepaliveConnections, &out.HTTPXMaxKeepaliveConnections
		*out = new(int32)
		**out = **in
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]corev1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Route != nil {
		in, out := &in.Route, &out.Route
		*out = new(RouteSpec)
		**out = **in
	}
}

func (in *GatewaySpec) DeepCopy() *GatewaySpec {
	if in == nil {
		return nil
	}
	out := new(GatewaySpec)
	in.DeepCopyInto(out)
	return out
}

func (in *RouteSpec) DeepCopyInto(out *RouteSpec) {
	*out = *in
}

func (in *RouteSpec) DeepCopy() *RouteSpec {
	if in == nil {
		return nil
	}
	out := new(RouteSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *DatabaseSpec) DeepCopyInto(out *DatabaseSpec) {
	*out = *in
	if in.Managed != nil {
		in, out := &in.Managed, &out.Managed
		*out = new(ManagedDatabaseSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.External != nil {
		in, out := &in.External, &out.External
		*out = new(ExternalDatabaseSpec)
		(*in).DeepCopyInto(*out)
	}
}

func (in *DatabaseSpec) DeepCopy() *DatabaseSpec {
	if in == nil {
		return nil
	}
	out := new(DatabaseSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *ManagedDatabaseSpec) DeepCopyInto(out *ManagedDatabaseSpec) {
	*out = *in
	out.StorageSize = in.StorageSize.DeepCopy()
	if in.StorageClassName != nil {
		in, out := &in.StorageClassName, &out.StorageClassName
		*out = new(string)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
}

func (in *ManagedDatabaseSpec) DeepCopy() *ManagedDatabaseSpec {
	if in == nil {
		return nil
	}
	out := new(ManagedDatabaseSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *ExternalDatabaseSpec) DeepCopyInto(out *ExternalDatabaseSpec) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
}

func (in *ExternalDatabaseSpec) DeepCopy() *ExternalDatabaseSpec {
	if in == nil {
		return nil
	}
	out := new(ExternalDatabaseSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *RedisSpec) DeepCopyInto(out *RedisSpec) {
	*out = *in
	if in.Managed != nil {
		in, out := &in.Managed, &out.Managed
		*out = new(ManagedRedisSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.External != nil {
		in, out := &in.External, &out.External
		*out = new(ExternalRedisSpec)
		(*in).DeepCopyInto(*out)
	}
}

func (in *RedisSpec) DeepCopy() *RedisSpec {
	if in == nil {
		return nil
	}
	out := new(RedisSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *ManagedRedisSpec) DeepCopyInto(out *ManagedRedisSpec) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
}

func (in *ManagedRedisSpec) DeepCopy() *ManagedRedisSpec {
	if in == nil {
		return nil
	}
	out := new(ManagedRedisSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *ExternalRedisSpec) DeepCopyInto(out *ExternalRedisSpec) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
}

func (in *ExternalRedisSpec) DeepCopy() *ExternalRedisSpec {
	if in == nil {
		return nil
	}
	out := new(ExternalRedisSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *NginxSpec) DeepCopyInto(out *NginxSpec) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
}

func (in *NginxSpec) DeepCopy() *NginxSpec {
	if in == nil {
		return nil
	}
	out := new(NginxSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *AuthSpec) DeepCopyInto(out *AuthSpec) {
	*out = *in
	if in.JWTSecretRef != nil {
		in, out := &in.JWTSecretRef, &out.JWTSecretRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
	if in.AdminPasswordRef != nil {
		in, out := &in.AdminPasswordRef, &out.AdminPasswordRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
}

func (in *AuthSpec) DeepCopy() *AuthSpec {
	if in == nil {
		return nil
	}
	out := new(AuthSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *FeaturesSpec) DeepCopyInto(out *FeaturesSpec) {
	*out = *in
	if in.UI != nil {
		in, out := &in.UI, &out.UI
		*out = new(bool)
		**out = **in
	}
	if in.AdminAPI != nil {
		in, out := &in.AdminAPI, &out.AdminAPI
		*out = new(bool)
		**out = **in
	}
	if in.A2A != nil {
		in, out := &in.A2A, &out.A2A
		*out = new(bool)
		**out = **in
	}
	if in.Plugins != nil {
		in, out := &in.Plugins, &out.Plugins
		*out = new(PluginsSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Catalog != nil {
		in, out := &in.Catalog, &out.Catalog
		*out = new(bool)
		**out = **in
	}
	if in.RustRuntime != nil {
		in, out := &in.RustRuntime, &out.RustRuntime
		*out = new(RustRuntimeSpec)
		**out = **in
	}
}

func (in *FeaturesSpec) DeepCopy() *FeaturesSpec {
	if in == nil {
		return nil
	}
	out := new(FeaturesSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *RustRuntimeSpec) DeepCopyInto(out *RustRuntimeSpec) {
	*out = *in
}

func (in *RustRuntimeSpec) DeepCopy() *RustRuntimeSpec {
	if in == nil {
		return nil
	}
	out := new(RustRuntimeSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *TestingSpec) DeepCopyInto(out *TestingSpec) {
	*out = *in
	if in.FastTimeServer != nil {
		in, out := &in.FastTimeServer, &out.FastTimeServer
		*out = new(bool)
		**out = **in
	}
	if in.FastTestServer != nil {
		in, out := &in.FastTestServer, &out.FastTestServer
		*out = new(bool)
		**out = **in
	}
	if in.SlowTimeServer != nil {
		in, out := &in.SlowTimeServer, &out.SlowTimeServer
		*out = new(bool)
		**out = **in
	}
	if in.A2AEchoAgent != nil {
		in, out := &in.A2AEchoAgent, &out.A2AEchoAgent
		*out = new(bool)
		**out = **in
	}
	if in.Locust != nil {
		in, out := &in.Locust, &out.Locust
		*out = new(LocustSpec)
		(*in).DeepCopyInto(*out)
	}
}

func (in *TestingSpec) DeepCopy() *TestingSpec {
	if in == nil {
		return nil
	}
	out := new(TestingSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *PluginsSpec) DeepCopyInto(out *PluginsSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ConfigMapRef != nil {
		in, out := &in.ConfigMapRef, &out.ConfigMapRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
	if in.CanOverrideAuthHeaders != nil {
		in, out := &in.CanOverrideAuthHeaders, &out.CanOverrideAuthHeaders
		*out = new(bool)
		**out = **in
	}
	if in.GitSource != nil {
		in, out := &in.GitSource, &out.GitSource
		*out = new(GitSourceSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.VolumeMounts != nil {
		in, out := &in.VolumeMounts, &out.VolumeMounts
		*out = make([]corev1.VolumeMount, len(*in))
		copy(*out, *in)
	}
	if in.Volumes != nil {
		in, out := &in.Volumes, &out.Volumes
		*out = make([]corev1.Volume, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *PluginsSpec) DeepCopy() *PluginsSpec {
	if in == nil {
		return nil
	}
	out := new(PluginsSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *GitSourceSpec) DeepCopyInto(out *GitSourceSpec) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
}

func (in *GitSourceSpec) DeepCopy() *GitSourceSpec {
	if in == nil {
		return nil
	}
	out := new(GitSourceSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *LocustSpec) DeepCopyInto(out *LocustSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]corev1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *LocustSpec) DeepCopy() *LocustSpec {
	if in == nil {
		return nil
	}
	out := new(LocustSpec)
	in.DeepCopyInto(out)
	return out
}
