# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from mcpgateway.transports.grpc_gen import mcp_runtime_pb2 as mcp__runtime__pb2

GRPC_GENERATED_VERSION = '1.78.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in mcp_runtime_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class McpRuntimeStub(object):
    """---------------------------------------------------------------------------
    Service definition
    ---------------------------------------------------------------------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Invoke = channel.unary_unary(
                '/contextforge.mcp.runtime.v1.McpRuntime/Invoke',
                request_serializer=mcp__runtime__pb2.McpRequest.SerializeToString,
                response_deserializer=mcp__runtime__pb2.McpResponse.FromString,
                _registered_method=True)
        self.InvokeStream = channel.unary_stream(
                '/contextforge.mcp.runtime.v1.McpRuntime/InvokeStream',
                request_serializer=mcp__runtime__pb2.McpRequest.SerializeToString,
                response_deserializer=mcp__runtime__pb2.McpChunk.FromString,
                _registered_method=True)
        self.CloseSession = channel.unary_unary(
                '/contextforge.mcp.runtime.v1.McpRuntime/CloseSession',
                request_serializer=mcp__runtime__pb2.McpRequest.SerializeToString,
                response_deserializer=mcp__runtime__pb2.McpResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/contextforge.mcp.runtime.v1.McpRuntime/HealthCheck',
                request_serializer=mcp__runtime__pb2.HealthRequest.SerializeToString,
                response_deserializer=mcp__runtime__pb2.HealthResponse.FromString,
                _registered_method=True)


class McpRuntimeServicer(object):
    """---------------------------------------------------------------------------
    Service definition
    ---------------------------------------------------------------------------

    """

    def Invoke(self, request, context):
        """Unary: POST /mcp — initialize, tools/call, tools/list, resources/*, prompts/*
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InvokeStream(self, request, context):
        """Server-streaming: GET /mcp — SSE / live-stream / resume
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseSession(self, request, context):
        """Unary: DELETE /mcp — session close
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Unary: health probe — used by Python entrypoint readiness check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_McpRuntimeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Invoke': grpc.unary_unary_rpc_method_handler(
                    servicer.Invoke,
                    request_deserializer=mcp__runtime__pb2.McpRequest.FromString,
                    response_serializer=mcp__runtime__pb2.McpResponse.SerializeToString,
            ),
            'InvokeStream': grpc.unary_stream_rpc_method_handler(
                    servicer.InvokeStream,
                    request_deserializer=mcp__runtime__pb2.McpRequest.FromString,
                    response_serializer=mcp__runtime__pb2.McpChunk.SerializeToString,
            ),
            'CloseSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseSession,
                    request_deserializer=mcp__runtime__pb2.McpRequest.FromString,
                    response_serializer=mcp__runtime__pb2.McpResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=mcp__runtime__pb2.HealthRequest.FromString,
                    response_serializer=mcp__runtime__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'contextforge.mcp.runtime.v1.McpRuntime', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('contextforge.mcp.runtime.v1.McpRuntime', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class McpRuntime(object):
    """---------------------------------------------------------------------------
    Service definition
    ---------------------------------------------------------------------------

    """

    @staticmethod
    def Invoke(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contextforge.mcp.runtime.v1.McpRuntime/Invoke',
            mcp__runtime__pb2.McpRequest.SerializeToString,
            mcp__runtime__pb2.McpResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InvokeStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/contextforge.mcp.runtime.v1.McpRuntime/InvokeStream',
            mcp__runtime__pb2.McpRequest.SerializeToString,
            mcp__runtime__pb2.McpChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloseSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contextforge.mcp.runtime.v1.McpRuntime/CloseSession',
            mcp__runtime__pb2.McpRequest.SerializeToString,
            mcp__runtime__pb2.McpResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contextforge.mcp.runtime.v1.McpRuntime/HealthCheck',
            mcp__runtime__pb2.HealthRequest.SerializeToString,
            mcp__runtime__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
