# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mcp_runtime.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'mcp_runtime.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11mcp_runtime.proto\x12\x1b\x63ontextforge.mcp.runtime.v1\">\n\x0eMcpAuthContext\x12\x0f\n\x07\x65ncoded\x18\x01 \x01(\t\x12\x1b\n\x13\x65xpires_at_epoch_ms\x18\x02 \x01(\x04\"\xc4\x02\n\nMcpRequest\x12\x0e\n\x06method\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t\x12\r\n\x05query\x18\x03 \x01(\t\x12\x0c\n\x04\x62ody\x18\x04 \x01(\x0c\x12\x45\n\x07headers\x18\x05 \x03(\x0b\x32\x34.contextforge.mcp.runtime.v1.McpRequest.HeadersEntry\x12\x11\n\tserver_id\x18\x06 \x01(\t\x12\x41\n\x0c\x61uth_context\x18\x07 \x01(\x0b\x32+.contextforge.mcp.runtime.v1.McpAuthContext\x12\x1a\n\x12\x61\x66\x66inity_forwarded\x18\x08 \x01(\x08\x12\x12\n\nsession_id\x18\t \x01(\t\x1a.\n\x0cHeadersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xa3\x01\n\x0bMcpResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x46\n\x07headers\x18\x02 \x03(\x0b\x32\x35.contextforge.mcp.runtime.v1.McpResponse.HeadersEntry\x12\x0c\n\x04\x62ody\x18\x03 \x01(\x0c\x1a.\n\x0cHeadersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"<\n\x08McpChunk\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x0c\n\x04\x64one\x18\x02 \x01(\x08\x12\x14\n\x0c\x65rror_status\x18\x03 \x01(\x05\"\x0f\n\rHealthRequest\"?\n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0c\n\x04mode\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\t2\x96\x03\n\nMcpRuntime\x12[\n\x06Invoke\x12\'.contextforge.mcp.runtime.v1.McpRequest\x1a(.contextforge.mcp.runtime.v1.McpResponse\x12`\n\x0cInvokeStream\x12\'.contextforge.mcp.runtime.v1.McpRequest\x1a%.contextforge.mcp.runtime.v1.McpChunk0\x01\x12\x61\n\x0c\x43loseSession\x12\'.contextforge.mcp.runtime.v1.McpRequest\x1a(.contextforge.mcp.runtime.v1.McpResponse\x12\x66\n\x0bHealthCheck\x12*.contextforge.mcp.runtime.v1.HealthRequest\x1a+.contextforge.mcp.runtime.v1.HealthResponseB2\n\x1f\x63om.contextforge.mcp.runtime.v1B\x0fMcpRuntimeProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mcp_runtime_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\037com.contextforge.mcp.runtime.v1B\017McpRuntimeProto'
  _globals['_MCPREQUEST_HEADERSENTRY']._loaded_options = None
  _globals['_MCPREQUEST_HEADERSENTRY']._serialized_options = b'8\001'
  _globals['_MCPRESPONSE_HEADERSENTRY']._loaded_options = None
  _globals['_MCPRESPONSE_HEADERSENTRY']._serialized_options = b'8\001'
  _globals['_MCPAUTHCONTEXT']._serialized_start=50
  _globals['_MCPAUTHCONTEXT']._serialized_end=112
  _globals['_MCPREQUEST']._serialized_start=115
  _globals['_MCPREQUEST']._serialized_end=439
  _globals['_MCPREQUEST_HEADERSENTRY']._serialized_start=393
  _globals['_MCPREQUEST_HEADERSENTRY']._serialized_end=439
  _globals['_MCPRESPONSE']._serialized_start=442
  _globals['_MCPRESPONSE']._serialized_end=605
  _globals['_MCPRESPONSE_HEADERSENTRY']._serialized_start=393
  _globals['_MCPRESPONSE_HEADERSENTRY']._serialized_end=439
  _globals['_MCPCHUNK']._serialized_start=607
  _globals['_MCPCHUNK']._serialized_end=667
  _globals['_HEALTHREQUEST']._serialized_start=669
  _globals['_HEALTHREQUEST']._serialized_end=684
  _globals['_HEALTHRESPONSE']._serialized_start=686
  _globals['_HEALTHRESPONSE']._serialized_end=749
  _globals['_MCPRUNTIME']._serialized_start=752
  _globals['_MCPRUNTIME']._serialized_end=1158
# @@protoc_insertion_point(module_scope)
